/**
 * One stylesheet source, two packages.
 *
 * The component CSS lives in packages/core, next to the markup it styles.
 * packages/react ships the same rules, because a React consumer must not have
 * to install the vanilla package to get styles. Copying by hand guarantees the
 * two drift, so the copy is generated here and the react files are artifacts.
 *
 * The aggregate `styles.css` in each package is generated for the same reason.
 * It used to be written by hand, and ten stylesheets — Text Field, Form
 * Message, Select, Combobox, Selection Popup and the whole navigation family —
 * were built, tested and then never imported, so a consumer loading the
 * package got markup with no rules to paint it. A generated list cannot fall
 * behind the directory it is generated from.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, basename, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const SRC = join(ROOT, 'packages/core/src');
const OUT = join(ROOT, 'packages/react/src/styles');

const sheets = [];
(function walk(dir) {
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full);
    else if (entry.endsWith('.css')) sheets.push(full);
  }
})(SRC);

mkdirSync(OUT, { recursive: true });
const banner = (from) =>
  `/* GENERATED from ${from} by packages/sync/src/build-styles.mjs — do not edit.\n` +
  `   Edit the source in packages/core/src and re-run \`npm run sync:styles\`. */\n`;

const names = new Set();
for (const sheet of sheets) {
  const name = basename(sheet);
  if (names.has(name)) throw new Error(`[ol8] two stylesheets are both called ${name}; the flat react/styles layout needs unique names`);
  names.add(name);
  const rel = sheet.slice(ROOT.length + 1);
  writeFileSync(join(OUT, name), banner(rel) + readFileSync(sheet, 'utf8'));
}

/* The load order the aggregate has always documented: tokens first because
   every rule reads their custom properties, then atoms before the molecules
   that compose them, then organisms, and the Gem material last because it
   adapts surfaces the component rules have already painted. Within one tier
   the sheets are independent, so they are ordered by name to stay stable. */
const TIERS = ['atoms', 'molecules', 'organisms', 'materials'];
const tierOf = (sheet) => TIERS.indexOf(relative(SRC, sheet).split('/')[0]);
const ordered = [...sheets].sort((a, b) => tierOf(a) - tierOf(b) || a.localeCompare(b));

const header = (pkg) =>
  `/* GENERATED by packages/sync/src/build-styles.mjs — do not edit.\n` +
  `   OneLi8 · complete stylesheet for @oneli8/${pkg}.\n` +
  `   Load order matters: tokens define the custom properties every rule reads,\n` +
  `   atoms before the molecules that compose them, and the Gem material last\n` +
  `   because it adapts surfaces the component rules have already painted. */\n` +
  `@import "@oneli8/tokens/css";\n`;

writeFileSync(join(ROOT, 'packages/core/styles.css'),
  header('core') + ordered.map(s => `@import "./${relative(join(ROOT, 'packages/core'), s)}";\n`).join(''));
writeFileSync(join(ROOT, 'packages/react/styles.css'),
  header('react') + ordered.map(s => `@import "./src/styles/${basename(s)}";\n`).join(''));

console.log(`✓ ${sheets.length} stylesheets -> packages/react/src/styles (source: packages/core/src)`);
console.log(`✓ aggregate styles.css generated for both packages (${ordered.length} imports each)`);
