// GENERATED by packages/sync/src/build-icons.mjs — do not edit by hand.
// Source: Figma "OneLi8 Design System — 1.0.0-beta.1", page Iconography,
// frame "Icon Library / Masters" (426:55). Re-run `npm run sync:icons`.

export interface Ol8IconEntry {
  /** Figma category segment: "Icon / <Category> / <Name>". */
  readonly category: 'action' | 'navigation' | 'status' | 'selection'
    | 'transport' | 'vitals' | 'maneuver';
  /** Node id of the 24px master in Figma, or null while it is a candidate. */
  readonly figmaNode: string | null;
  /** True until the master is approved and mapped to a Figma node. */
  readonly candidate?: boolean;
  /** Semantic registry controls RTL mirroring (per Iconography documentation). */
  readonly mirrorInRTL: boolean;
  /** The ink Figma baked into the master, discarded in favour of currentColor. */
  readonly sourceInk: string | null;
  /** Drawing instructions in the canonical 24-unit source space. */
  readonly body: string;
}

export declare const OL8_ICON_VIEWBOX: '0 0 24 24';
export declare const OL8_ICONS: {
  readonly "add": Ol8IconEntry;
  readonly "caution": Ol8IconEntry;
  readonly "check": Ol8IconEntry;
  readonly "chevron-down": Ol8IconEntry;
  readonly "chevron-up": Ol8IconEntry;
  readonly "clear": Ol8IconEntry;
  readonly "close": Ol8IconEntry;
  readonly "copy": Ol8IconEntry;
  readonly "critical": Ol8IconEntry;
  readonly "forward": Ol8IconEntry;
  readonly "heart": Ol8IconEntry;
  readonly "informative": Ol8IconEntry;
  readonly "loading": Ol8IconEntry;
  readonly "maneuver-right": Ol8IconEntry;
  readonly "mixed": Ol8IconEntry;
  readonly "pause": Ol8IconEntry;
  readonly "play": Ol8IconEntry;
  readonly "positive": Ol8IconEntry;
  readonly "search": Ol8IconEntry;
  readonly "selected-dot": Ol8IconEntry;
  readonly "skip-back": Ol8IconEntry;
  readonly "skip-forward": Ol8IconEntry;
  readonly "visibility-closed": Ol8IconEntry;
  readonly "visibility-open": Ol8IconEntry;
};
export type Ol8IconName = keyof typeof OL8_ICONS;
