// GENERATED by packages/sync/src/build-icons.mjs — do not edit by hand.
// Source: Figma "Oneli8 Design System — 1.0.0-beta.1", page Iconography,
// frame "Icon Library / Masters" (426:55). Re-run `npm run sync:icons`.

export interface Ol8IconEntry {
  /** Figma category segment: "Icon / <Category> / <Name>". */
  readonly category: 'action' | 'navigation' | 'status' | 'selection';
  /** Node id of the 24px master in the Figma source file. */
  readonly figmaNode: string;
  /** Semantic registry controls RTL mirroring (per Iconography documentation). */
  readonly mirrorInRTL: boolean;
  /** Drawing instructions in the canonical 24-unit source space. */
  readonly body: string;
}

export declare const OL8_ICON_VIEWBOX: '0 0 24 24';
export declare const OL8_ICONS: {
  readonly "add": Ol8IconEntry;
  readonly "caution": Ol8IconEntry;
  readonly "chevron-down": Ol8IconEntry;
  readonly "chevron-up": Ol8IconEntry;
  readonly "clear": Ol8IconEntry;
  readonly "close": Ol8IconEntry;
  readonly "critical": Ol8IconEntry;
  readonly "forward": Ol8IconEntry;
  readonly "informative": Ol8IconEntry;
  readonly "loading": Ol8IconEntry;
  readonly "positive": Ol8IconEntry;
  readonly "search": Ol8IconEntry;
  readonly "visibility-closed": Ol8IconEntry;
  readonly "visibility-open": Ol8IconEntry;
};
export type Ol8IconName = keyof typeof OL8_ICONS;
